version: '3.5'
services:
  web:
    image: tomcat:latest
    links:
      - mvn
    ports:
      - "8081:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps

  mvn:
    build: war-build
    volumes:
      - ./target:/tmp/build/

#volumes:
#  target:
