FROM maven:3.8.2-jdk-11 as maven
RUN apt-get update
RUN apt-get install git -y
RUN mkdir /tmp/homework7
WORKDIR "/tmp/homework7"
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR "/tmp/homework7/boxfuse-sample-java-war-hello"
RUN mvn package
